- name: "Use string/proto ..."
  set_fact:
    fwrule: "{{ {} | combine({ 'proto': rule | split('/') | last }) }}"
    rule_parsed: true

- name: "Append rule ..."
  set_fact:
    fwrules: "{{ fwrules + [ fwrule ] }}"
