---
- name: "Interfaces ..."
  block:
    - name: "Verify network interfaces ..."
      include_tasks: "interface/verify.yaml"
      loop: "{{ host.network.interface }}"
      loop_control:
        label: "{{ interface.type | default(interface.name) | default('error') }}"
        loop_var: interface
      when: host.network.interface is defined

    - name: "List of configuration files ...."
      set_fact:
        managed_files: [ '50-*' ]

    - name: "Configure network interfaces ..."
      include_tasks: "interface/configure.yaml"
      loop: "{{ host.network.interface }}"
      loop_control:
        label: "{{ interface.type | default(interface.name) }}"
        loop_var: interface

    - name: "Looking for unmanaged files in /etc/systemd/network directory ..."
      find:
        paths: /etc/systemd/network
        file_type: file
        excludes: "{{ managed_files }}"
      register: network_cleanup

    - name: "Delete unmanaged files form /etc/systemd/network ..."
      file:
        path: "{{ cleanup.path }}"
        state: absent
      loop: "{{ network_cleanup.files }}"
      loop_control:
        label: "{{ cleanup.path }}"
        loop_var: cleanup
      register: ifcleanup
  when: host.network.interface is defined

- name: "Role status ..."
  set_fact:
    wyga_system_network:
      changed: "{{ ifchanged | default(false) or ifcleanup.changed | default(false) }}"
