---
- name: "SYSTEMD / Journal ..."
  file:
    path: "/etc/systemd/journald.conf.d"
    state: directory

- name: "Default storage type (auto) ..."
  set_fact:
    journal_storage: "{{ host.setup.systemd.journal.storage | default('auto') }}"

- name: "Normalize storage type (disk) ..."
  set_fact:
    journal_storage: "persistent"
  when: journal_storage in [ 'disk' ]

- name: "Normalize storage type (volatile) ..."
  set_fact:
    journal_storage: "volatile"
  when: journal_storage in [ 'ram' ]

- name: "SYSTEMD / Journal / Storage ..."
  template:
    src: "journald/host-policy"
    dest: "/etc/systemd/journald.conf.d/host-policy.conf"
    group: root
    owner: root
    mode: 0644
  vars:
    systemd_journal_storage: "{{ journal_storage }}"
    systemd_journal_maxuse: "{{ host.setup.systemd.journal.maxuse | default('default') }}"
  notify:
    - systemd-journald

- name: "SYSTEMD / Journal / Cleanup ..."
  set_fact:
    wyga_journal_registred_config: "{{ wyga_journal_registred_config | unique }}"

- name: "SYSTEMD / Journal / Looking for unmanaged files in /etc/systemd/journald.conf.d directory ..."
  find:
    paths: "/etc/systemd/journald.conf.d"
    file_type: file
    excludes: "{{ wyga_journal_registred_config }}"
  register: journald_cleanup

- name: "SYSTEMD / Delete unmanaged files form /etc/systemd/journald.conf.d ..."
  file:
    path: "{{ cleanup.path }}"
    state: absent
  loop: "{{ journald_cleanup.files }}"
  loop_control:
    label: "{{ cleanup.path }}"
    loop_var: cleanup
  notify:
    - systemd-journald
