---
- name: "SYSTEMD / Service / systemd-networkd-wait-online ..."
  file:
    path: "/etc/systemd/system/systemd-networkd-wait-online.service.d"
    state: directory

- name: "SYSTEMD / Service / systemd-networkd-wait-online ..."
  template:
    src: "service/wait-online/custom"
    dest: "/etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf"
    group: root
    owner: root
    mode: 0644
  vars:
    wait_online: "{{ systemdConfig.service.wait_online if systemdConfig.service.wait_online is defined else systemdConfig.service['wait-online'] }}"
