---
- name: "Create {{ host_policy_dir }}/policy ..."
  block:
    - name: "Create {{ host_policy_dir }} directory ..."
      file:
        path: "{{ host_policy_dir }}"
        state: directory
    - name: "Create policy marker ..."
      copy:
        content: "{{ host.hostname }}"
        dest: "{{ host_policy_dir }}/policy"
        mode: "0600"
        owner: "root"
        group: "root"
      register: first_run

    - name: "Trigger any pending handlers ..."
      meta: flush_handlers

    - name: "Trigger reboot ..."
      debug:
        msg: "."
      changed_when: true
      notify:
        - reboot-host
      when: first_run.changed
