---
- name: "Simple group definition ..."
  block:
    - name: "Create default group attributes ..."
      set_fact:
        _wum_value: {}
    - name: "Make sure system attribute is present for group {{ wum_target }} ..."
      set_fact:
        _wum_value: "{{ _wum_value | combine({'system': false}) }}"

    - name: "Make sure unique attribute is present for group {{ wum_target }} ..."
      set_fact:
        _wum_value: "{{ _wum_value | combine({'unique': true}) }}"

    - name: "Append {{ wum_target }} to group dictonary ..."
      set_fact:
        wum_groups: "{{ wum_groups|default({}) | combine({wum_target: _wum_value}) }}"
  when: "wum_target is string"

- name: "Extended group definition ..."
  block:
    - name: "Evaluate extended group object ..."
      set_fact:
        _wum_target: "{{ lookup('dict',wum_target) }}"

    - name: "Normalize extended group object ..."
      set_fact:
        _wum_value: "{{ _wum_target.value }}"

    - name: "Make sure system attribute is present for group {{ _wum_target.key }} ..."
      set_fact:
        _wum_value: "{{ _wum_value | combine({'system': false}) }}"
      when: _wum_value.system is not defined

    - name: "Make sure unique attribute is present for group {{ _wum_target.key }} ..."
      set_fact:
        _wum_value: "{{ _wum_value | combine({'unique': true}) }}"
      when: _wum_value.unique is not defined

    - name: "Append {{ _wum_target.key }} to group dictonary ..."
      set_fact:
        wum_groups: "{{ wum_groups|default({}) | combine({_wum_target.key: _wum_value}) }}"
  when: "wum_target is mapping"
