- name: "Configure /etc/ssh/sshd_config.d/authorized.conf ..."
  template:
    src: "ssh/authorized"
    dest: "/etc/ssh/sshd_config.d/authorized.conf"
    group: root
    owner: root
    mode: 0644
  vars:
    ssh_user_cert: "{{ host.setup.ssh.user.certificate | default(true) }}"
  notify: restart-ssh

- name: "Update registred configurations ..."
  set_fact:
    wyga_ssh_registred_config: "{{ wyga_ssh_registred_config + ['authorized.conf' ] }}"
