- name: "Create user ..."
  include_tasks: "user-create.yaml"
  loop: "{{ wum_users | dict2items }}"
  loop_control:
    loop_var: target
    label: "{{ target.key }}"

- name: "Cleanup users ..."
  include_tasks: "user-remove.yaml"
