---
- name: "SWAP / Select swap file ..."
  set_fact:
    swap_file: "{{ host.setup.swap.file | default('/swap.space') }}"

- name: "SWAP / check if swap file exists ..."
  stat:
    path: "{{ swap_file }}"
  register: swap_file_present

- name: "SWAP / Create swap file ..."
  block:
    - name: "SWAP / Create swapfile ..."
      file:
        path: "{{ swap_file }}"
        state: touch
        mode: 0600
        owner: root
        group: root

    - name: "SWAP / Allocate swap file ..."
      command: fallocate -l "{{ host.setup.swap.size | default('1GiB') }}" "{{ swap_file }}"

    - name: "SWAP / Initialize swap file ..."
      command: mkswap -qf "{{ swap_file }}"
  when: not swap_file_present.stat.exists

- name: "SWAP / Add swap file to /etc/fstab ..."
  mount:
    name: none
    src: "{{ swap_file }}"
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
    state: present
  register: swap_fstab

- name: "SWAP / Enable swap space ..."
  block:
    - name: "SWAP / reload systemd config ..."
      systemd:
        daemon_reload: true

    - name: "SWAP / enable swap space ..."
      command: swapon -a
  when: swap_fstab.changed
