---
- name: "SYSTEMD / Journal /var/log/journal fix permisions ..."
  command: systemd-tmpfiles --create --prefix /var/log/journal
  when: journal_storage == 'persistent'

- name: "SYSTEMD / Journal restart ..."
  systemd:
    state: restarted
    name: systemd-journald

- name: "SYSTEMD / Journal /var/log/journal purge..."
  file:
    path: "/var/log/journal"
    state: absent
  when: journal_storage == 'volatile'

- name: "SYSTEMD / Journal /var/log/journal switch ..."
  command: journalctl --flush
  when: journal_storage == 'persistent'
