---
- name: "SYSTEMD / Journal restart ..."
  systemd:
    state: restarted
    name: systemd-journald

- name: "SYSTEMD / Journal /var/log/journal purge..."
  file:
    path: "/var/log/journal"
    state: absent
  when: journal_storage == 'volatile'

# /var/log/journal is recreated with wrong permisions (and enabled Copy On Write on btrfs)
# don't know why ...
- name: "SYSTEMD / Journal / Flush ..."
  systemd:
    state: restarted
    name: systemd-journal-flush
  when: journal_storage == 'persistent'

#- name: "SYSTEMD / Journal /var/log/journal switch ..."
#  command: journalctl --flush
#  when: journal_storage == 'persistent'
