---
- name: "SYSTEMD / sysstat ..."
  systemd:
    name: sysstat
    enabled: "{{ true if host.setup.systemd.service.sysstat.enable | default(false) else false }}"
    masked: false
    daemon_reload: true
    state: "{{ 'restarted' if host.setup.systemd.service.sysstat.enable | default(false) else 'stopped' }}"
