- name: "Docker Configuration ..."
  block:
    - name: "Create /etc/docker ..."
      file:
        path: /etc/docker
        state: directory
        group: root
        owner: root
        mode: 0755
      register: etcdocker

    - name: "Docker Configuration ..."
      template:
        src: "docker/daemon.json"
        dest: "/etc/docker/daemon.json"
        group: root
        owner: root
        mode: 0600
      vars:
        config: "{{ host.setup.docker }}"
      register: docker_updated

    - name: "Restart docker service ..."
      systemd:
        name: docker
        enabled: true
        daemon_reload: true
        state: restarted
        masked: no
      when: docker_updated.changed and not etcdocker.changed

  when: host.setup.docker is defined
