---
- name: "Bridge configuration ..."
  set_fact:
    bridge: "{{ bridge_entry }}"
  when: bridge_entry.use is not defined

- name: "systemd-networkd / bridge / verify configuration (use) ..."
  block:
    - name: "Verify used template ..."
      assert:
        that:
          - >
            bridge_entry.use is regex('(?i)^clone/([a-f0-9]{2}:){5}[a-f0-9]{2}$')
            or bridge_entry.use is regex('(?i)^clone/([a-z0-9@.+_-]){1,16}$')
        msg: "Unable to continue, check interface configuration for {{ bridge_entry.use }} ..."

    - name: "Load template ..."
      include_tasks: "bridge/use.yaml"

  when: bridge_entry.use is defined

- name: "Cast slave as list ..."
  set_fact:
    bridge: "{{ bridge | combine( { 'slave': [ bridge.slave ] }, recursive=true) }}"
  when: bridge.slave is defined and bridge.slave is string

- name: "systemd-networkd / bridge / verify configuration ..."
  assert:
    that:
      - bridge.name is defined
      - bridge.slave | type_debug == 'list'
    msg: "Unable to continue, check interface configuration ..."

- name: "systemd-networkd / bridge / verify configuration / clone ..."
  assert:
    that:
      - bridge.slave | length == 1
    msg: "Unable to continue, check interface configuration ..."
  when: bridge.mac is defined and bridge.mac == 'clone'

- name: "systemd-networkd / bridge / verify configuration / mac ..."
  assert:
    that:
      - bridge.mac is string
      - bridge.mac is regex('^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$')
    msg: "Unable to continue, check interface configuration ..."
  when: bridge.mac is defined and bridge.mac != 'clone'
