---
- name: "Load template for loopback ..."
  include_tasks: "use/interface/loopback.yaml"
  when: interface_entry.use == 'loopback'

- name: "Load template for dummy ..."
  include_tasks: "use/interface/dummy.yaml"
  vars:
    if_name: "{{ interface_entry.use[6:] }}"
  when: interface_entry.use is regex('^dummy/')

- name: "Load template for dhcp/mac ..."
  include_tasks: "use/interface/mac-dhcp.yaml"
  vars:
    ifparam: "{{ interface_entry.use[5:] }}"
  when: interface_entry.use is regex('(?i)^dhcp/([a-f0-9]{2}:){5}[a-f0-9]{2}')

- name: "Load template for dhcp/interface ..."
  include_tasks: "use/interface/name-dhcp.yaml"
  vars:
    ifparam: "{{ interface_entry.use[5:] }}"
  when: interface_entry.use is regex('(?i)^dhcp/([a-z0-9@.+_-]){1,16}$')

- name: "Load template for static/mac ..."
  include_tasks: "use/interface/mac-static.yaml"
  vars:
    ifparam: "{{ interface_entry.use[7:] }}"
  when: interface_entry.use is regex('(?i)^static/([a-f0-9]{2}:){5}[a-f0-9]{2}$')

- name: "Load template for static/interface ..."
  include_tasks: "use/interface/name-static.yaml"
  vars:
    ifparam: "{{ interface_entry.use[7:] }}"
  when: interface_entry.use is regex('(?i)^static/([a-z0-9@.+_-]){1,16}$')

- name: "Load template for dns/interface/domains ..."
  block:
    - name: "Extract parameters ..."
      set_fact:
        dns_template: "{{ interface_entry.use | regex_findall('(?i)^dns/([a-z0-9@.+_-]{1,16})/(.+)$') | flatten }}"
    - name: "Load template for dns/interface/domains ..."
      include_tasks: "use/interface/dns-only.yaml"
      vars:
        ifparam: "{{ dns_template[0] }}"
        ifdomains: "{{ dns_template[1] | split('/') | map('regex_replace', '^', '~') | join(' ') }}"
  when: interface_entry.use is regex('(?i)^dns/([a-z0-9@.+_-]{1,16})/(.+)$')

- name: "Load template for ether/dhcp ..."
  include_tasks: "use/interface/ether-dhcp.yaml"
  when: interface_entry.use == 'ether/dhcp'

- name: "Load template for ether/virtio/dhcp ..."
  include_tasks: "use/interface/ether-virtio-dhcp.yaml"
  when: interface_entry.use == 'ether/virtio/dhcp'

- name: "Load template for ether/kvm/dhcp ..."
  include_tasks: "use/interface/ether-virtio-dhcp.yaml"
  when: interface_entry.use == 'ether/kvm/dhcp'

- name: "Load template for ether/vif/dhcp ..."
  include_tasks: "use/interface/ether-vif-dhcp.yaml"
  when: interface_entry.use == 'ether/vif/dhcp'

- name: "Load template for ether/xen/dhcp ..."
  include_tasks: "use/interface/ether-vif-dhcp.yaml"
  when: interface_entry.use == 'ether/xen/dhcp'

- name: "Load template for ether/ena/dhcp ..."
  include_tasks: "use/interface/ether-ena-dhcp.yaml"
  when: interface_entry.use == 'ether/ena/dhcp'

- name: "Load template for ether/vm/dhcp ..."
  include_tasks: "use/interface/ether-vm-dhcp.yaml"
  when: interface_entry.use == 'ether/vm/dhcp'

- name: "Load template for wlan/dhcp ..."
  include_tasks: "use/interface/wlan-dhcp.yaml"
  when: interface_entry.use == 'wlan/dhcp'
