---
- name: "Check if OS is supported ..."
  assert:
    that:
      - target_distribution in [ 'ubuntu', 'debian' ]
      - target_distribution_version in [ "20.04", "22.04", "24.04", "12" ]
    fail_msg: "Unsupported distribution: {{ target_distribution | capitalize }} {{ target_distribution_version }}"
    quiet: true

- name: "Configuration ..."
  set_fact:
    package_list: []
    prerequisite_list: []
    repository_list: []
    require_list: []
    purge_list: []

- name: "..."
  fail:
    msg: "missing install_packages ..."
  when: install_packages is not defined

- name: "Slurp packages list ..."
  set_fact:
    packages: "{{ install_packages }}"

- name: "Remove packages not intended for the {{ target_distribution }} distribution ..."
  set_fact:
    packages: "{{ packages | reject('regex','^.+@(?!' ~ target_distribution ~ ').+$') | list }}"

- name: "Strip target distribution suffix ..."
  set_fact:
    packages: "{{ packages | map('regex_replace', '@' ~ target_distribution ~ '$', '') | list }}"

- name: "Select packages to purge ..."
  set_fact:
    purge_list: "{{ packages | select('regex', '^-') | map('regex_replace', '^-', '') | list }}"
    packages: "{{ packages | reject('regex', '^-') | list }}"

- name: "Prepare packages list ..."
  set_fact:
     package_list: "{{ package_list + [ { 'name': package, 'manifest': playbook_dir + '/local/packages/' + target_distribution + '/' + target_distribution_version + '/' + package } ] + [ { 'name': package, 'manifest': role_path + '/files/packages/' + target_distribution + '/' + target_distribution_version + '/' + package } ] }}"
  loop: "{{ packages }}"
  loop_control:
    loop_var: package
    label: "{{ package }}"

- name: "Process packages ... (PASS 1) ..."
  include_tasks: "packages/process-package.yml"
  vars:
    process_require: true
  loop: "{{ package_list }}"
  when: "package.manifest is exists"
  loop_control:
    loop_var: package
    label: "{{ package.name }}"

- name: "Normalize require list ..."
  set_fact:
    require_list: "{{ require_list | unique }}"

# Simple dependency processing (no circular dependencies)
- name: "Process require list ..."
  block:
    - name: "Initialize packages list ..."
      set_fact:
        package_list: []
    - name: "Prepare package list (require) ..."
      set_fact:
        package_list: "{{ package_list + [ { 'name': package, 'manifest': playbook_dir + '/site/packages/' + target_distribution + '/' + target_distribution_version + '/' + package } ] + [ { 'name': package, 'manifest': role_path + '/files/packages/' + target_distribution + '/' + target_distribution_version + '/' + package } ] }}"
        packages: "{{ packages + [ package ] }}"
      loop: "{{ require_list }}"
      loop_control:
        loop_var: package
      when: package not in packages

    - name: "Process packages ... (PASS 2) ..."
      include_tasks: "packages/process-package.yml"
      vars:
        process_require: false
      loop: "{{ package_list }}"
      when: "package.manifest is exists"
      loop_control:
        loop_var: package
        label: "{{ package.name }}"
  when: require_list | length > 0

- name: "Normalize prerequisite list ..."
  set_fact:
    prerequisite_list: "{{ prerequisite_list | unique }}"

- name: "Normalize repository list ..."
  set_fact:
    repository_list: "{{ repository_list | unique }}"

- name: "Normalize purge list ..."
  set_fact:
    purge_list: "{{ purge_list | difference(packages) | difference(prerequisite_list) | unique }}"

- name: "Normalize packages list ..."
  set_fact:
    packages: "{{ packages | unique }}"

- name: "Remove meta packages from list ..."
  set_fact:
    packages: "{{ packages | reject('regex', '^\\.') | list }}"

- name: "Information ..."
  debug:
    msg:
      - "TARGET:        {{ target_distribution | capitalize }} {{ target_distribution_version }}"
      - "PACKAGES:      {{ packages }}"
      - "REPOSITORIES:  {{ repository_list }}"
      - "PREREQUISITES: {{ prerequisite_list }}"
      - "PURGE:         {{ purge_list }}"

- name: "Install prerequisites packages ..."
  include_tasks: "packages/install-prerequisites.yml"
  when: prerequisite_list | length > 0

- name: "Purge packages ..."
  include_tasks: "packages/purge-packages.yml"
  when: purge_list | length > 0

- name: "Install prerequisites packages ..."
  include_tasks: "packages/install-prerequisites.yml"
  when: prerequisite_list | length > 0

- name: "Install respositories ..."
  include_role:
    name: wyga/install-repository
  loop: "{{ repository_list }}"
  when: repository_list | length > 0
  loop_control:
    loop_var: repository_name

- name: "."
  debug:
    msg: "Installing packages ..."

- name: "Install packages ..."
  include_tasks: "packages/install-packages.yml"
