# Weird issue with cache update - manual refresh
#- name: "Update packages cache ..."
#  command: apt-get update -qq
#  changed_when: false

- name: "Update packages cache ..."
  apt:
    update_cache: true
    cache_valid_time: 1
  changed_when: false
  register: _action
  retries: 10
  until: _action is success

- name: "Install packages ..."
  apt:
    name: "{{ __packages }}"
    state: latest
    install_recommends: no
    autoclean: yes
  register: _action
  retries: 25
  until: _action is success or ('Failed to lock apt for exclusive operation' not in _action.msg and '/var/lib/dpkg/lock' not in _action.msg)
