- name: "Install packages ..." 
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: no
    autoclean: yes
    update_cache: yes
  register: _action
  retries: 25
  until: _action is success or ('Failed to lock apt for exclusive operation' not in _action.msg and '/var/lib/dpkg/lock' not in _action.msg)

- name: "Cleanup ..." 
  shell: apt-get clean
  register: _action
  retries: 25
  changed_when: false
  until: _action is success or ('Failed to lock apt for exclusive operation' not in _action.msg and '/var/lib/dpkg/lock' not in _action.msg)
