---
- name: "Load manifest for {{ ip_package.name }} ..."
  include_vars:
    file: "{{ ip_package.manifest }}"
    name: loaded_manifest

- name: "Append prerequisite packages ..."
  set_fact:
    prerequisite_list: "{{ prerequisite_list + loaded_manifest.prerequisite }}"
  when: loaded_manifest.prerequisite is defined

- name: "Append repositories ..."
  set_fact:
    repository_list: "{{ repository_list + loaded_manifest.repository }}"
  when: loaded_manifest.repository is defined

- name: "Append required packages ..."
  set_fact:
    require_list: "{{ require_list + loaded_manifest.require }}"
  when: process_require | default(false) and loaded_manifest.require is defined

- name: "Append purged packages ..."
  set_fact:
    purge_list: "{{ purge_list + loaded_manifest.purge }}"
  when: loaded_manifest.purge is defined

- name: "Append enabled services ..."
  set_fact:
    enable_services: "{{ enable_services + loaded_manifest.enable }}"
  when: loaded_manifest.enable is defined
