- name: "Purge packages ..." 
  apt:
    name: "{{ purge_list }}"
    state: absent
    autoremove: yes
    purge: yes
  register: _action
  retries: 25
  until: _action is success or ('Failed to lock apt for exclusive operation' not in _action.msg and '/var/lib/dpkg/lock' not in _action.msg)
