#jinja2: trim_blocks: True, lstrip_blocks: True
pki:
  ca: |
    {{ instance.ca.all | trim | indent(4) }}
  cert: /etc/site/vpn/{{ instance.name }}/host.crt
  key: /etc/site/vpn/{{ instance.name }}/host.key
{% if instance.ca.migrate is defined %}
  initiating_version: {{ instance.ca.migrate.version }}
{% endif %}
{% if instance.config.blocklist is defined %}
  blocklist:
{% for block in instance.config.blocklist %}
    - {{ block }}
{% endfor %}
{% endif %}

static_host_map:
{% for host in instance.config.lighthouse.hosts.keys() %}
  "{{ host }}":
  {% for map in instance.config.lighthouse.hosts[host] %}
    - "{{ map }}"
  {% endfor %}
{% endfor %}

lighthouse:
{% if instance.lighthouse %}
  am_lighthouse: true
  {% if instance.config.lighthouse.dns.enable | default(true) %}
  serve_dns: true
  dns:
    host: {{ instance.config.lighthouse.dns.bind if instance.config.lighthouse.dns.bind is defined else instance.ip | first | ansible.utils.ipaddr('address')  }}
    port: 53
  {% endif %}
{% endif %}
  interval: {{ instance.config.lighthouse.interval | default(60) }}
  hosts:
    {% if not instance.lighthouse %}
    {% for host in instance.config.lighthouse.hosts.keys() %}
    - {{ host }}
    {% endfor %}
    {% endif %}

{% if vpn_instance.port > 0 %}
listen:
  port: {{ vpn_instance.port }}

{% elif instance.lighthouse %}
listen:
  port: 4242

{% endif %}
punchy:
  punch: true
  respond: true
  target_all_remotes: true

cipher: {{ instance.config.cipher | default('aes') }}
{% if instance.network.adjacent | length > 0 %}

preferred_ranges:
{% for neighbour in instance.network.adjacent %}
  - "{{ neighbour }}"
{% endfor %}
{% endif %}

relay:
  {% if not instance.lighthouse %}
  relays:
  {% for relay in instance.config.lighthouse.hosts.keys() %}
    - "{{ relay }}"
  {% endfor %}
  {% if instance.network.relay == false %}
  use_relays: false
  {% endif %}
  {% else %}
  am_relay: true
  use_relays: false
  {% endif %}

tun:
  dev: {{ instance.config.tun.dev | default('overlay0') }}
  drop_local_broadcast: true
  drop_multicast: true
{% if instance.network.route | length > 0 %}
  unsafe_routes:
    {% for via in instance.network.route.keys() if via not in instance.ip | map('ansible.utils.ipaddr', 'address') %}
    {% for route in instance.network.route[via] if route.to not in instance.network.local %}
    - route: {{ route.to }}
      via: {{ via }}
      metric: {{ route.metric | default(1000) }}
      install: true
    {% endfor %}
    {% endfor %}
{% endif %}
{%if 'system' in instance.network.routing %}
  use_system_route_table: true
{% endif %}

logging:
  level: fatal
  format: text

tunnels:
  drop_inactive: true
  inactivity_timeout: 120m

firewall:
  outbound_action: reject
  inbound_action: reject

  outbound:
    - port: any
      proto: any
      host: any

    - port: any
      proto: any
      host: any
      local_cidr: 0.0.0.0/0

  inbound:
    - port: any
      proto: any
      host: any

    - port: any
      proto: any
      host: any
      local_cidr: 0.0.0.0/0
