#!/usr/bin/env bash
set -eufo pipefail
IFS=$'\t\n'

if [[ -z ${{ '{' }}{{ tl_name | upper }}_NEBULA_CA:-} ]]
then
  printf -- "ERROR: {{ tl_name | upper }}_NEBULA_CA not set ..."
  exit 10
fi

nebula-cert sign \
            -ca-crt "${{ '{' }}{{ tl_name | upper }}_NEBULA_CA}/ca.crt" \
            -ca-key "${{ '{' }}{{ tl_name | upper }}_NEBULA_CA}/ca.key" \
            -in-pub "{{ playbook_dir }}/vpn/inbox/{{ tl_name }}-{{ template_hostname }}.pub" \
            -out-crt "{{ playbook_dir }}/vpn/inbox/{{ tl_name }}-{{ template_hostname }}.crt" \
            -name "{{ tl_hostname }}.{{ template_domain }}" \
{% if tl_subnets | length > 0 %}
            -subnets "{{ ','.join(tl_subnets) }}" \
{% endif %}
            -ip "{{ tl_ip }}"
