---
- name: "Process allow/any ..."
  set_fact:
    fwrules: "{{ fwrules + [ { 'any': 'any' } ] }}"
    rule_parsed: true
  when: rule.allow == 'any'

- name: "Process allow/registry-mirror ..."
  set_fact:
    fwrules: "{{ fwrules + fwrule_icmp }}"
    rule_parsed: true
  vars:
    fwrule_icmp:
      - { 'dport': '80', 'match': 'tcp', 'proto': 'tcp', 'dst': [ '100.100.100.100' ] }
  when: rule.allow == 'registry-mirror' or rule.allow == 'registry/mirror'

- name: "Process allow/icmp ..."
  set_fact:
    fwrules: "{{ fwrules + fwrule_icmp }}"
    rule_parsed: true
  vars:
    fwrule_icmp:
      - { 'icmptype': 'destination-unreachable', 'match': 'icmp', 'proto': 'icmp' }
      - { 'icmptype': 'echo-request', 'match': 'icmp', 'proto': 'icmp' }
      - { 'icmptype': 'time-exceeded', 'match': 'icmp', 'proto': 'icmp' }
      - { 'icmptype': 'parameter-problem', 'match': 'icmp', 'proto': 'icmp' }
  when: rule.allow == 'icmp'

- name: "Process allow/http ..."
  set_fact:
    fwrules: "{{ fwrules + fwrule_http }}"
    rule_parsed: true
  vars:
    fwrule_http:
      - { 'dport': '80', 'match': 'tcp', 'proto': 'tcp' }
      - { 'dport': '443', 'match': 'tcp', 'proto': 'tcp' }
      - { 'dport': '443', 'match': 'udp', 'proto': 'udp' }
  when: rule.allow == 'http'

- name: "Process allow/nebula ..."
  block:
    - name: "Append allow/nebula rules ..."
      set_fact:
        fwrule_nebula:
          - { 'dport': '4242', 'match': 'udp', 'proto': 'udp' }
    - name: "Append rule ..."
      set_fact:
        fwrules: "{{ fwrules + fwrule_nebula }}"
        rule_parsed: true
  when: rule.allow == 'nebula'

- name: "Process allow/if ..."
  set_fact:
    fwrules: "{{ fwrules + [{'iface': allow_iface}] }}"
    rule_parsed: true
  vars:
    allow_iface: "{{ rule.allow.split('/')[1] }}"
  when: rule.allow is regex('(?i)^if/[a-z][a-z0-9-]{1,18}[a-z0-9]$')

- name: "Process allow/port/proto ..."
  set_fact:
    fwrules: "{{ fwrules + [ { 'proto': allow_proto, 'dport': allow_port } ] }}"
    rule_parsed: true
  vars:
    allow_port: "{{ rule.allow.split('/')[0] | replace('-', ':') }}"
    allow_proto: "{{ rule.allow.split('/')[1] }}"
  when: rule.allow is regex('(?i)^[0-9]+(-[0-9]+)?/([a-z]+)$')

- name: "Process allow/port/proto/if ..."
  set_fact:
    fwrules: "{{ fwrules + [ { 'proto': allow_proto, 'iface': allow_iface, 'dport': allow_port } ] }}"
    rule_parsed: true
  vars:
    allow_port: "{{ rule.allow.split('/')[0] | replace('-', ':') }}"
    allow_proto: "{{ rule.allow.split('/')[1] }}"
    allow_iface: "{{ rule.allow.split('/')[2] }}"
  when: rule.allow is regex('(?i)^[0-9]+(-[0-9]+)?/[a-z]+/([a-z][a-z0-9-]{1,18}[a-z0-9]|[a-z][a-z0-9]+\+)$')

- name: "Process allow/vpn ..."
  block:
    - name: "Append allow/vpn rules ..."
      set_fact:
        fwrule_vpn:
          - { 'iface': 'overlay0' }
          - { 'dport': '4242', 'match': 'udp', 'proto': 'udp' }
    - name: "Append rule ..."
      set_fact:
        fwrules: "{{ fwrules + fwrule_vpn }}"
        rule_parsed: true
  when: rule.allow == 'vpn'

- name: "Process allow/ssh ..."
  block:
    - name: "Extract config name ..."
      set_fact:
        ssh_firewall_file: "{{ rule.allow | split('/') | last | lower }}"
      when: rule.allow is regex('(?i)^ssh/[a-z][a-z0-9-]{1,18}[a-z0-9]$')

    - name: "Select 'any' config name ..."
      set_fact:
        ssh_firewall_file: "any"
      when: rule.allow is regex('(?i)^ssh$')

    - name: "Find ssh hosts file ..."
      set_fact:
        ssh_firewall_path: "{{ query('first_found', params) | first | default('') }}"
      vars:
        ssh_firewall_dir: "{{ playbook_dir }}/site/{{ host_policy_site }}/firewall/ssh"
        params:
          skip: true
          files:
            - "{{ ssh_firewall_dir }}/{{ host.hostname }}/{{ ssh_firewall_file }}.yaml"
            - "{{ ssh_firewall_dir }}/{{ host.hostname }}/{{ ssh_firewall_file }}"
            - "{{ ssh_firewall_dir }}/{{ ssh_firewall_file }}.yaml"
            - "{{ ssh_firewall_dir }}/{{ ssh_firewall_file }}"
      when: ssh_firewall_file != 'any'

    - name: "ERROR ..."
      fail:
        msg:
          - "Unable to find ssh hosts file for {{ rule.allow }}"
      when: ssh_firewall_file != 'any' and ssh_firewall_path == ''

    - name: "Load ssh hosts ..."
      include_vars:
        file: "{{ ssh_firewall_path }}"
        name: ssh_firewall_loaded
      when: ssh_firewall_file != 'any'

    - name: "Select loaded ssh hosts ..."
      set_fact:
        ssh_firewall_hosts: "{{ ssh_firewall_loaded }}"
      when: ssh_firewall_file != 'any'

    - name: "Define 'any' ..."
      set_fact:
        ssh_firewall_hosts:
          hosts:
            - 0.0.0.0/0
      when: ssh_firewall_file == 'any'

    - name: "ERROR ..."
      fail:
        msg:
          - "Invalid ssh hosts file {{ ssh_firewall_path }}"
      when: ssh_firewall_hosts.hosts is not defined and ssh_firewall_hosts.firewall.allow is not defined

    - name: "Append rule ..."
      set_fact:
        fwrules: "{{ fwrules + [ { 'match': 'tcp', 'proto': 'tcp', 'src': ssh_firewall_hosts.hosts, 'dport': 22 } ] }}"
      when: ssh_firewall_hosts.hosts is defined

    - name: "Process extended ssh hosts ..."
      block:
        - name: "ERROR ..."
          fail:
            msg:
              - "Missing src in {{ ssh_firewall_path }}"
          when: ssh_firewall_hosts.firewall.allow | rejectattr('src', 'defined') | list | length > 0

        - name: "Append rules ..."
          set_fact:
            fwrules: "{{ fwrules + [ ssh_firewall_rule ] }}"
          loop: "{{ ssh_firewall_hosts.firewall.allow }}"
          loop_control:
            loop_var: ssh_firewall_entry
            label: "{{ ssh_firewall_entry }}"
          vars:
            ssh_firewall_rule: "{{
              { 'match': 'tcp', 'proto': 'tcp', 'src': [ ssh_firewall_entry.src ] | flatten, 'dport': 22 }
              | combine({ 'dst': [ ssh_firewall_entry.dst ] | flatten } if ssh_firewall_entry.dst is defined else {})
              | combine({ 'iface': ssh_firewall_entry.iface } if ssh_firewall_entry.iface is defined else {})
              | combine({ 'comment': ssh_firewall_entry.comment } if ssh_firewall_entry.comment is defined else {})
            }}"
      when: ssh_firewall_hosts.hosts is not defined

    - name: "Rule parsed ..."
      set_fact:
        rule_parsed: true
  when: rule.allow is regex('(?i)^ssh/[a-z][a-z0-9-]{1,18}[a-z0-9]$') or rule.allow is regex('(?i)^ssh$')
