---
- name: "Check if Distribution is supported ..."
  assert:
    that:
      - target_distribution in ['ubuntu','debian']
      - target_distribution_version in ['18.04','20.04','22.04','12']
    fail_msg: "Unsupported distribution: {{ target_distribution }} {{ target_distribution_version }}"
    quiet: true

- name: "Configure /etc/apt/apt.conf.d/99-host-policy ..."
  template:
    src: "apt/host-policy"
    dest: "/etc/apt/apt.conf.d/99-host-policy"
    group: root
    owner: root
    mode: 0644
  register: apt_host_policy

- name: "Configure /etc/apt/sources.list ..."
  template:
    src: "apt/{{ target_distribution }}/{{ target_distribution_version }}/sources.list"
    dest: "/etc/apt/sources.list"
    group: root
    owner: root
    mode: 0644
  vars:
    mirror: "{{ host.setup.apt.mirror | default('pl') }}"
    backports: "{{ host.setup.apt.sources.backports | default(false) | bool }}"
    universe: "{{ host.setup.apt.sources.universe | default(true) | bool }}"
    multiverse: "{{ host.setup.apt.sources.multiverse | default(false) | bool }}"
    contrib: "{{ host.setup.apt.sources.contrib | default(true) | bool }}"
    nonfree: "{{ host.setup.apt.sources.nonfree | default(true) | bool }}"
    nonfreefirmware: "{{ host.setup.apt.sources.nonfreefirmware | default(true) | bool }}"
  register: apt_sources

# Digitial Ocean's Debian
- name: "Cleanup (Debian) ...."
  file:
    path: "/etc/apt/sources.list.d/debian.sources"
    state: absent

- name: "Cleanup apt ..."
  shell: "find /var/lib/apt/lists /var/cache/apt -type f -delete && apt-get clean"
  when: apt_host_policy.changed or apt_sources.changed
