- name: "Install gitlab-runner apt repository ..."
  copy:
    src: "repository/gitlab-runner/ubuntu/22.04/{{ repo_file.src }}"
    dest: "{{ repo_file.dst }}"
    group: root
    owner: root
    mode: 0644
    force: yes
  loop:
    - { 'src': 'gitlab-runner.list', 'dst': '/etc/apt/sources.list.d/gitlab-runner.list' }
    - { 'src': 'gitlab-runner.gpg',  'dst': '/usr/share/keyrings/gitlab-runner.gpg' }
  loop_control:
    loop_var: repo_file
    label: "{{ repo_file }}"
