---
- name: "APT / {{ target_distribution | capitalize }} {{ target_distribution_version }} / /etc/apt/sources.list.d ..."
  file:
    path: "/etc/apt/sources.list.d"
    state: directory

- name: "APT / {{ target_distribution | capitalize }} {{ target_distribution_version }} / /etc/apt/sources.list ..."
  template:
    src: "apt/{{ target_distribution }}/{{ target_distribution_version }}/sources.list"
    dest: "/etc/apt/sources.list"
    group: root
    owner: root
    mode: 0644

- name: "APT / {{ target_distribution | capitalize }} {{ target_distribution_version }} / /etc/apt/sources.list.d/{{ target_distribution }}.sources ..."
  template:
    src: "apt/{{ target_distribution }}/{{ target_distribution_version }}/sources"
    dest: "/etc/apt/sources.list.d/{{ target_distribution }}.sources"
    group: root
    owner: root
    mode: 0644
  vars:
    mirror: "{{ 'http://deb.debian.org/debian' if host.setup.apt.mirror | default('pl') == 'cdn' else 'http://ftp.' ~ host.setup.apt.mirror | default('pl') ~ '.debian.org/debian' }}"
    backports: "{{ host.setup.apt.sources.backports | default(true) | bool }}"
  register: apt_sources

- name: "APT / {{ target_distribution | capitalize }} {{ target_distribution_version }} / /etc/apt/sources.list cleanup ..."
  file:
    path: "/etc/apt/{{ apt_source_list }}"
    state: absent
  loop:
    - "sources.list~"
    - "sources.list.bak"
  loop_control:
    loop_var: apt_source_list
    label: "/etc/apt/{{ apt_source_list }}"
