- name: "KIT / {{ inventory_hostname }} ..."
  set_fact:
    kit_target: "{{ playbook_dir }}/kits/{{ inventory_hostname }}"
  when: host.hostname is not defined

- name: "KIT / {{ host.hostname }} ..."
  set_fact:
    kit_target: "{{ playbook_dir }}/kits/{{ host.hostname }}"
  when: host.hostname is defined

- name: "KIT / {{ kit_target }} / Execute ..."
  include_tasks: kit.yaml
  when: kit_target is directory
