- name: "Check migration status ..."
  slurp:
    src: /etc/site/network/mode
  register: net_migration_status
  ignore_errors: true
  no_log: true

- name: "Current migration mode ..."
  set_fact:
    net_migration_mode: "{{ (net_migration_status.content | b64decode | trim) if net_migration_status.content is defined else '' }}"

- name: "Migration ..."
  block:
    - name: "Debian 14 network migration ..."
      include_tasks: migrate/debian-14.yaml
      when: platform.distribution == 'debian' and platform.version == '14'

    - name: "Debian network migration ..."
      include_tasks: migrate/debian.yaml
      when: platform.distribution == 'debian' and platform.version != '14'

    - name: "Ubuntu network migration ..."
      include_tasks: migrate/ubuntu.yaml
      when: platform.distribution == 'ubuntu'
  when: net_migration_mode != 'systemd-networkd'
