- name: "ANSIBLE / Install pipx ..."
  include_role:
    name: wyga/install-package-override
  vars:
    packages:
      - pipx

- name: "ASIBLE / Install ansible ..."
  community.general.pipx:
    name: ansible
    state: latest
    install_deps: true
    include_injected: true
    global: true

- name: "ASIBLE / Incject packages  ..."
  community.general.pipx:
    name: ansible
    state: inject
    install_deps: true
    global: true
    inject_packages:
      - netaddr
      - argcomplete
