- name: "Disable networking.service ..."
  systemd:
    name: networking.service
    enabled: false
  ignore_errors: true

- name: "Enable systemd-networkd.service ..."
  systemd:
    name: systemd-networkd.service
    enabled: true

- name: "Remove /etc/network/interfaces ..."
  file:
    path: /etc/network/interfaces
    state: absent

- name: "Purge packages ..."
  apt:
    name:
      - ifupdown
      - isc-dhcp-client
      - dhcp-client
    state: absent
    autoremove: yes
    purge: yes
  register: _action
  retries: 25
  until: _action is success or ('Failed to lock apt for exclusive operation' not in _action.msg and '/var/lib/dpkg/lock' not in _action.msg)

# Digital Ocean
- name: "Cleanup providers files ..."
  file:
    path: "{{ provider_cleanup }}"
    state: absent
  loop:
    - /etc/udev/rules.d/70-persistent-net.rules
    - /etc/udev/rules.d/99-digitalocean-automount.rules
  loop_control:
    loop_var: provider_cleanup
    label: "{{ provider_cleanup }}"

- name: "Create /etc/site/network directory ..."
  file:
    path: "/etc/site/network"
    state: directory

- name: "Create migration marker ..."
  copy:
    content: "systemd-networkd"
    dest: "/etc/site/network/mode"
    mode: "0644"
    owner: "root"
    group: "root"
