- name: "Ensure /etc/site exists ..."
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    path: "/etc/site"

- name: "Ensure /etc/site/vpn exists ..."
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    path: "/etc/site/vpn"

- name: "VPN Instance ..."
  set_fact:
    vpn_instance: "{{ vpn_entry | combine({ 'hostname': vpn_entry.hostname if vpn_entry.hostname is defined else host.hostname }) }}"
    vpn_all_ca: ""
    node_subnets: []

- name: "Verify IP configuration ..."
  assert:
    that:
      - vpn_instance.ip is iterable

- name: "IP address pool .."
  set_fact:
    vpn_instance: "{{ vpn_instance | combine({'ip': [ vpn_instance.ip ]}) }}"
  when: vpn_instance.ip is string

- name: "Validate IP addresses ..."
  assert:
    that:
      - (vpn_instance.ip | map('string') | map('ansible.utils.ipaddr') | select | list | length) == (vpn_instance.ip | length)
    fail_msg: "Invalid IP addresses ..."

- name: "Load VPN configuration ..."
  include_vars:
    file: "vpn/nebula/{{ vpn_instance.name }}/config.yaml"
    name: vpn

- name: "Verify VPN configuration ..."
  assert:
    that:
      - vpn.pki.ca is defined
      - vpn.pki.ca is iterable

- name: "Verify vpn.pki.ca configuration ..."
  assert:
    that:
      - vpn_ca.crt is defined
      - vpn_ca.crt is string
      - vpn_ca.crt | expandvars is file
  loop: "{{ vpn.pki.ca }}"
  loop_control:
    loop_var: vpn_ca
    label: "{{ vpn_ca.crt | default('MISSING') }}"

- name: "Validate Lighthouse IP addresses ..."
  assert:
    that:
      - (vpn.lighthouse.hosts.keys() | list | map('string') | map('ansible.utils.ipaddr') | select | list | length) == (vpn.lighthouse.hosts.keys() | list | length)
    fail_msg: "Invalid Lighthouse IP address ..."

- name: "Select default CA ..."
  set_fact:
    vpn_default_ca: "{{ (vpn.pki.ca  | selectattr('default', 'defined') | selectattr('default', 'equalto', true) | list | first) | default(vpn.pki.ca | first, true) }}"

- name: "Select migrate CA ..."
  set_fact:
    vpn_migrate_ca: "{{ (vpn.pki.ca  | selectattr('migrate', 'defined') | selectattr('migrate', 'equalto', true) | list | first) | default({}) }}"

- name: "Concat all CA certs ..."
  set_fact:
    vpn_all_ca: "{{ vpn_all_ca ~ (lookup('ansible.builtin.file', ca.crt | expandvars) | regex_replace('\n+$', '')) ~ '\n' }}"
  loop: "{{ vpn.pki.ca }}"
  loop_control:
    loop_var: ca
    label: "{{ ca.crt }}"

- name: "Node subnets ..."
  include_tasks: subnets.yaml
  loop: "{{ vpn.route | dict2items }}"
  loop_control:
    loop_var: nebula_routes
    label: "{{ nebula_routes.key }}"
  when:
    - vpn.route is defined
    - nebula_routes.key in (vpn_instance.ip | map('ansible.utils.ipaddr', 'address') | list)

- name: "Add any defined subnets ..."
  set_fact:
    node_subnets: "{{ node_subnets + vpn_entry.subnet.add }}"
  when: vpn_entry.subnet.add is defined

- name: "Update CA for instance ..."
  set_fact:
    vpn_instance: >-
      {{ vpn_instance | combine({
        'lighthouse': (vpn_instance.ip | map('ansible.utils.ipaddr', 'address') | list) | intersect(vpn.lighthouse.hosts.keys() | list) | length > 0,
        'config': vpn,
        'domain': vpn.domain | default('vpn'),
        'fqdn': vpn_instance.hostname ~ '.' ~ vpn.domain | default('vpn'),
        'port': vpn_instance.port | default(0),
        'network': {
          'relay': vpn_instance.relay | default(true),
          'adjacent': vpn_instance.adjacents | default([]),
          'subnets': (vpn.subnets if vpn.subnets is defined else node_subnets) | sort,
          'route': (vpn.route | default({}) | combine(vpn_entry.route | default({}), recursive=true)) if 'disable' not in (vpn_entry.routing | default([])) else [],
          'local': vpn_entry.local | default([]),
          'routing': vpn_entry.routing | default([]),
        },
        'ca': {
          'crt': vpn_default_ca.crt | expandvars,
          'hash': lookup('ansible.builtin.file', vpn_default_ca.crt | expandvars) | hash('sha256'),
          'agent': vpn_default_ca.agent | default(false) | bool,
          'encrypted': vpn_default_ca.encrypted | default(false) | bool,
          'version': vpn_default_ca.version | default(2),
          'all': vpn_all_ca
        }
        | combine({'key': vpn_default_ca.key | expandvars} if vpn_default_ca.key is defined else {})
        | combine({
          'migrate': {
            'crt': vpn_migrate_ca.crt | expandvars,
            'agent': vpn_migrate_ca.agent | default(false) | bool,
            'version': vpn_migrate_ca.version | default(2),
          }} if vpn_migrate_ca | length > 0 else {})
      }, recursive=true) }}

#- debug:
#    var: vpn_instance

- name: "Ensure /etc/site/vpn/{{ vpn_instance.name }} exists ..."
  file:
    state: directory
    owner: root
    group: root
    mode: 0700
    path: "/etc/site/vpn/{{ vpn_instance.name }}"

- name: "Prepare VPN instance ..."
  command: nebula-vpn setup {{ vpn_instance.name }}
  changed_when: false
  environment:
    NEBULA_UNATTENDED_SETUP: true

- name: "Certificate marker (test) ..."
  template:
    src: "vpn/nebula/certificate"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/certificate"
    group: root
    owner: root
    mode: 0600
  vars:
    instance: "{{ vpn_instance }}"
  check_mode: true
  register: certificate_changed

- name: "Regenerate/generate host certificate ..."
  set_fact:
    generate_cert: "{{ certificate_changed.changed }}"

- name: "Check if host certificate is present ..."
  block:
    - name: "Is host certificate present ..."
      stat:
        path: "/etc/site/vpn/{{ vpn_instance.name }}/host.crt"
      register: host_certificate
    - name: "Generate certificate? ..."
      set_fact:
        generate_cert: "{{ not host_certificate.stat.exists }}"
  when: not generate_cert

- name: "Generate new host certificate ..."
  block:
    - name: "Prepare inbox folder ..."
      file:
        path: "{{ playbook_dir }}/vpn/inbox"
        state: directory
      delegate_to: localhost

    - name: "Cleanup ..."
      file:
        path: "{{ file }}"
        state: absent
      loop:
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.pub"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt.migrate"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}-sign"
      loop_control:
        loop_var: file
        label: "{{ file | basename }}"
      delegate_to: localhost

    - name: "Fetch host.pub file ..."
      fetch:
        src: "/etc/site/vpn/{{ vpn_instance.name }}/host.pub"
        dest: "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.pub"
        flat: true

    - name: "Sign Certicate ..."
      include_tasks: sign.yaml

    - name: "Copy host certificate ..."
      copy:
        src: "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt"
        dest: "/etc/site/vpn/{{ vpn_instance.name }}/host.crt"
      notify:
        - nebula-vpn-restart

    - name: "Cleanup ..."
      file:
        path: "{{ file }}"
        state: absent
      loop:
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.pub"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt.migrate"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}-sign"
      loop_control:
        loop_var: file
        label: "{{ file | basename }}"
      delegate_to: localhost
  when: generate_cert

- name: "Certificate marker ..."
  template:
    src: "vpn/nebula/certificate"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/certificate"
    group: root
    owner: root
    mode: 0600
  vars:
    instance: "{{ vpn_instance }}"
  register: state_changed
  notify:
    - nebula-vpn-restart

- name: "Save change state ..."
  set_fact:
    restart_me: "{{ state_changed.changed }}"

- name: "Configuration ..."
  template:
    src: "vpn/nebula/config.yml"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/config.yaml"
    group: root
    owner: root
    mode: 0600
  vars:
    instance: "{{ vpn_instance }}"
  register: state_changed
  notify:
    - nebula-vpn-restart

- name: "Update change state ..."
  set_fact:
    restart_me: "{{ restart_me or state_changed.changed }}"

- name: "Enable nebula-vpn@{{ vpn_instance.name }}.service ..."
  systemd:
    name: "nebula-vpn@{{ vpn_instance.name }}.service"
    enabled: true
    daemon_reload: true
    state: started
    masked: no

- name: "Cleanup ..."
  file:
    path: "{{ file }}"
    state: absent
  loop:
    - "/etc/site/vpn/{{ vpn_instance.name }}/ca.crt"
  loop_control:
    loop_var: file
    label: "{{ file | basename }}"
