- name: "Append hostname ..."
  set_fact:
    vpn_instance: "{{ vpn_entry | combine({ 'hostname': host.hostname}) }}"
  when: vpn_entry.hostname is not defined

- name: "Append hostname ..."
  set_fact:
    vpn_instance: "{{ vpn_entry }}"
  when: vpn_entry.hostname is defined

- name: "Load VPN configuration ..."
  include_vars:
    file: "vpn/nebula/{{ vpn_instance.name }}/config.yaml"
    name: vpn

- name: "Prepare variables ..."
  set_fact:
    am_lighthouse: "{{ true if vpn_instance.ip | ipaddr('address') in vpn.lighthouse.hosts.keys() else false }}"
    ip_valid: "{{ true if vpn_instance.ip | ipaddr('address') | ipaddr(vpn.network) else false }}"
    node_subnets: []

- name: "Check is node IP belongs to VPN network ..."
  fail:
    msg: "Wrong VPN IP ..."
  when: not ip_valid

- name: "Preapre VPN instance ..."
  command: /usr/sbin/nebula-vpn-setup {{ vpn_instance.name }}
  changed_when: false

- name: "Node subnets ..."
  include_tasks: subnets.yaml
  loop: "{{ vpn.routing | dict2items }}"
  loop_control:
    loop_var: nebula_routes
    label: "{{ nebula_routes.key }}"
  when: vpn.routing is defined and vpn_instance.ip | ipaddr('address') == nebula_routes.key

- name: "Certificate marker (test) ..."
  template:
    src: "vpn/nebula/certificate"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/certificate"
    group: root
    owner: root
    mode: 0600
  vars:
    ip: "{{ vpn_instance.ip }}"
    name: "{{ vpn_instance.hostname }}"
    subnets: "{{ (vpn.subnets if vpn.subnets is defined else node_subnets) | sort }}"
    domain: "{{ vpn.domain | default('vpn') }}"
  check_mode: true
  register: certificate_changed

- name: "Copy CA certificate (test) ..."
  copy:
    src: "vpn/nebula/{{ vpn_instance.name }}/ca.crt"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/ca.crt"
  check_mode: true
  register: ca_changed

- name: "Regenerate/generate host certificate ..."
  set_fact:
    generate_cert: "{{ certificate_changed.changed or ca_changed.changed }}"

- name: "Check if host certificate is present ..."
  block:
    - name: "Is host certificate present ..."
      stat:
        path: "/etc/site/vpn/{{ vpn_instance.name }}/host.crt"
      register: host_certificate
    - name: "Genereate certifiate? ..."
      set_fact:
        generate_cert: "{{ not host_certificate.stat.exists }}"
  when: not generate_cert

- name: "Generate new host certificate ..."
  block:
    - name: "Prepare inbox folder ..."
      file:
        path: "{{ playbook_dir }}/vpn/inbox"
        state: directory
      delegate_to: localhost

    - name: "Cleanup ..."
      file:
        path: "{{ file }}"
        state: absent
      loop:
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.pub"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}-sign"
      loop_control:
        loop_var: file
        label: "{{ file | basename }}"
      delegate_to: localhost

    - name: "Fetch host.pub file ..."
      fetch:
        src: "/etc/site/vpn/{{ vpn_instance.name }}/host.pub"
        dest: "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.pub"
        flat: true

    - name: "Manual certicate sign ..."
      include_tasks: sign_cert_manual.yaml
      when: vpn.ca.encrypted | default(true)

    - name: "Automatic certicate sign ..."
      include_tasks: sign_cert_auto.yaml
      when: not vpn.ca.encrypted | default(true)

    - name: "Copy host certificate ..."
      copy:
        src: "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt"
        dest: "/etc/site/vpn/{{ vpn_instance.name }}/host.crt"
      notify:
        - nebula-vpn-restart

    - name: "Cleanup ..."
      file:
        path: "{{ file }}"
        state: absent
      loop:
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.pub"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt"
        - "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}-sign"
      loop_control:
        loop_var: file
        label: "{{ file | basename }}"
      delegate_to: localhost
  when: generate_cert

- name: "Certificate marker ..."
  template:
    src: "vpn/nebula/certificate"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/certificate"
    group: root
    owner: root
    mode: 0600
  vars:
    ip: "{{ vpn_instance.ip }}"
    name: "{{ vpn_instance.hostname }}"
    subnets: "{{ (vpn.subnets if vpn.subnets is defined else node_subnets) | sort }}"
    domain: "{{ vpn.domain | default('vpn') }}"
  register: state_changed
  notify:
    - nebula-vpn-restart

- name: "Save change state ..."
  set_fact:
    restart_me: "{{ state_changed.changed }}"

- name: "Copy CA certificate ..."
  copy:
    src: "vpn/nebula/{{ vpn_instance.name }}/ca.crt"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/ca.crt"
  register: state_changed
  notify:
    - nebula-vpn-restart

- name: "Update change state ..."
  set_fact:
    restart_me: "{{ restart_me or state_changed.changed }}"

- name: "Configuration ..."
  template:
    src: "vpn/nebula/config.yml"
    dest: "/etc/site/vpn/{{ vpn_instance.name }}/config.yaml"
    group: root
    owner: root
    mode: 0600
  vars:
    ip: "{{ vpn_instance.ip | ipaddr('address') }}"
    name: "{{ vpn_instance.name }}"
    adjacent: "{{ vpn_instance.adjacents | default([]) }}"
    am_lighthouse: "{{ am_lighthouse }}"
    use_relays: "{{ vpn_instance.relay | default(false) }}"
    vpn: "{{ vpn }}"
    port: "{{ vpn_instance.port if vpn_instance.port is defined else 4242 }}"
    systemroute: "{{ true if vpn_instance.route is defined and vpn_instance.route == 'system' else false }}"
  register: state_changed
  notify:
    - nebula-vpn-restart

- name: "Update change state ..."
  set_fact:
    restart_me: "{{ restart_me or state_changed.changed }}"

- name: "Stop old instance ..."
  block:
    - name: "Enable nebula-vpn@{{ vpn_instance.name }}.service ..."
      systemd:
        name: "nebula-vpn@{{ vpn_instance.name }}.service"
        enabled: true
        daemon_reload: true
        state: started
        masked: no
        no_block: true

    - name: "Disable nebula-vpn-dns.service ..."
      systemd:
        name: "nebula-vpn-dns.service"
        enabled: false
        daemon_reload: true
        state: stopped
        masked: yes
    - name: "Disable nebula.service ..."
      systemd:
        name: "nebula.service"
        enabled: false
        daemon_reload: true
        state: stopped
        masked: yes
  rescue:
    - name: "Continue ..."
      debug: msg="Continue ..."
  when: nebula_stop_old_instance is defined

- name: "Enable nebula-vpn@{{ vpn_instance.name }}.service ..."
  systemd:
    name: "nebula-vpn@{{ vpn_instance.name }}.service"
    enabled: true
    daemon_reload: true
    state: started
    masked: no
