- name: "Prepare variables ..."
  set_fact:
    nebula_instance_config: "vpn/nebula/{{ vpn_instance.name }}"
    nebula_certificate_base: "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}"

- name: "Sign via ssh-agent ..."
  block:
    - name: "Check if Nebula CA key is present for {{ vpn_instance.name }} ..."
      command:  nebula-tool sign ssh -ca-crt "{{ vpn_instance.ca.crt }}" -test
      register: nebula_ca_key_present
      ignore_errors: yes
      changed_when: false
      retries: 25
      delegate_to: localhost
      until: nebula_ca_key_present is success
    - name: "Nebula CA key not loaded ..."
      fail:
        msg: "Nebula CA key for '{{ vpn_instance.name }}' is not loaded ..."
      when: nebula_ca_key_present.rc != 0
    - name: "Sign host certificate via ssh-agent ..."
      command: >
        nebula-tool sign ssh -ca-crt "{{ vpn_instance.ca.crt }}"
                          -in-pub  "{{ nebula_certificate_base }}.pub"
                          -out-crt "{{ nebula_certificate_base }}.crt"
                          -name "{{ vpn_instance.fqdn }}"
                          -unsafe-networks "{{ ','.join(vpn_instance.network.subnets) }}"
                          -ip "{{ ','.join(vpn_instance.ip) }}"
                          -version "{{ vpn_instance.ca.version }}"
      delegate_to: localhost
    - name: "Migrate CA path ..."
      include_tasks: sign_cert_ssh_migrate.yaml
      when: vpn_instance.ca.migrate is defined

  when: vpn_instance.ca.agent | default(false)

- name: "Sign via nebula-cert ..."
  block:
    - name: "Manual certificate sign ..."
      include_tasks: sign_cert_manual.yaml
      when: vpn_instance.ca.encrypted | default(true)

    - name: "Automatic certificate sign ..."
      include_tasks: sign_cert_auto.yaml
      when: not vpn_instance.ca.encrypted | default(true)
  when: not vpn_instance.ca.agent | default(false)

- name: "Get host certificate ..."
  command: nebula-cert print -path {{ nebula_certificate_base }}.crt
  register: nebula_host_certificate
  delegate_to: localhost

- name: "Register certificate fingerprint ..."
  set_fact:
    nebula_host_fingerprint: "{{ (nebula_host_certificate.stdout | from_json).fingerprint }}"

- name: "Ensure {{ nebula_instance_config }}/certificate/{{ host.hostname }} exists ..."
  file:
    state: directory
    mode: 0755
    path: "{{ nebula_instance_config }}/certificate/{{ host.hostname }}"
  delegate_to: localhost

- name: "Save host certificate ..."
  copy:
    src: "{{ nebula_certificate_base }}.crt"
    dest: "{{ nebula_instance_config }}/certificate/{{ host.hostname }}/{{ nebula_host_fingerprint }}.crt"
  delegate_to: localhost

# Merge certs
- name: "Merge migrated certs ..."
  block:
    - name: "Set variable ..."
      set_fact:
        migrated_cert: ""

    - name: "Concat all CA certs ..."
      set_fact:
        migrated_cert: "{{ migrated_cert  ~ (lookup('ansible.builtin.file', cert) | regex_replace('\n+$', '')) ~ '\n' }}"
      loop:
        - "{{ nebula_certificate_base }}.crt"
        - "{{ nebula_certificate_base }}.crt.migrate"
      loop_control:
        loop_var: cert
        label: "{{ cert }}"

    - name: "Save host certificate ..."
      copy:
        content: "{{ migrated_cert }}"
        dest: "{{ nebula_certificate_base }}.crt"
      delegate_to: localhost

    - name: "Save host certificate ..."
      file:
        path: "{{ nebula_certificate_base }}.crt.migrate"
        state: absent
      delegate_to: localhost
  when: vpn_instance.ca.migrate is defined
