---
- name: "Generate sign script ..."
  template:
    src: "vpn/nebula/sign-certificate"
    dest: "{{ nebula_certificate_base }}-sign"
    mode: 0755
  vars:
    template_ip: "{{ vpn_instance.ip }}"
    template_name: "{{ vpn_instance.name }}"
    template_hostname: "{{ vpn_instance.hostname }}"
    template_subnets: "{{ (vpn.subnets if vpn.subnets is defined else node_subnets) | sort }}"
    template_domain: "{{ vpn.domain | default('vpn') }}"
  delegate_to: localhost

- name: "Waiting for {{ nebula_certificate_base }}.crt ..."
  debug: msg="..."

- name: "Waiting for host.crt"
  wait_for:
    path: "{{ nebula_certificate_base }}.crt"
    state: present
    timeout: 300
  delegate_to: localhost
