---
- name: "Verify migration state ..."
  assert:
    that:
      - vpn_instance.ca.migrate is not defined
    fail_msg: "Migration not supported ..."

- name: "Verify CA configuration ..."
  assert:
    that:
      - vpn_default_ca.key is defined
      - vpn_default_ca.key is string
      - vpn_default_ca.key | expandvars is file

- name: "Generate sign script ..."
  template:
    src: "vpn/nebula/sign-certificate"
    dest: "{{ nebula_certificate_base }}-sign"
    mode: 0755
  vars:
    instance: "{{ vpn_instance }}"
  delegate_to: localhost

- name: "Waiting for {{ nebula_certificate_base }}.crt ..."
  debug: msg="..."

- name: "Waiting for host.crt"
  wait_for:
    path: "{{ nebula_certificate_base }}.crt"
    state: present
    timeout: 300
  delegate_to: localhost
