---
- name: "Get Nebula CA path ..."
  set_fact:
    ca_path: "{{ lookup('env', vpn_instance.name | upper ~ '_NEBULA_CA') }}"

- name: "{{ vpn_instance.name | upper }}_NEBULA_CA not set ..."
  fail:
    msg: "missing env {{ vpn_instance.name | upper }}_NEBULA_CA ..."
  when: ca_path | length == 0

- name: "Sign host certicate ..."
  command: >
    nebula-cert sign  -ca-crt {{ ca_path }}/ca.crt
                      -ca-key {{ ca_path }}/ca.key
                      -in-pub {{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.pub
                      -out-crt {{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt
                      -name {{ vpn_instance.hostname }}.{{ vpn.domain | default('vpn') }}
                      -subnets "{{ ','.join(node_subnets) }}"
                      -ip {{ vpn_instance.ip }}
  connection: local
