---
- name: "Generate sign script ..."
  template:
    src: "vpn/nebula/sign-certificate"
    dest: "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}-sign"
    mode: 0755
  vars:
    ip: "{{ vpn_instance.ip }}"
    name: "{{ vpn_instance.name }}"
    hostname: "{{ vpn_instance.hostname }}"
    subnets: "{{ node_subnets | sort }}"
    domain: "{{ vpn.domain | default('vpn') }}"
  connection: local

- name: "Waiting for vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt ..."
  debug: msg="..."

- name: "Waiting for host.crt"
  wait_for:
    path: "{{ playbook_dir }}/vpn/inbox/{{ vpn_instance.name }}-{{ vpn_instance.hostname }}.crt"
    state: present
    timeout: 300
  connection: local
