---

- include_tasks: "public-key-exist.yaml"
  loop: "{{wum_users | dict2items}}"
  loop_control:
    loop_var: pool
    label: "{{ pool.key }}"

- include_tasks: "update-pool.yaml"
  loop: "{{wum_users | dict2items}}"
  loop_control:
    loop_var: pool
    label: "{{ pool.key }}"

- include_tasks: "remove-keys.yaml"
