---
- name: "Create/update group {{ target.key }}"
  ansible.builtin.group:
    name: "{{ target.key }}"
    gid: "{{ target.value.gid | default(omit) }}"
    non_unique: "{{ not target.value.unique }}"
    system: "{{ target.value.system }}"
    state: present

- name: "Create managed group state directory ..."
  file:
    path: "{{wum_group_managed}}"
    state: directory

- name: "Mark group {{ target.key }} as managed ..."
  copy:
    dest: "{{wum_group_managed }}/{{target.key}}"
    content: "{{ target.key }}"
    owner: root
    group: root
    mode:  0400
