---
#- name: "Select users..."
#  set_fact:
#    files_regexp: "^({{ pool.value.authorized | join('|') }})$"

- name: "Create temporary key directory..."
  ansible.builtin.tempfile:
    state: directory
    suffix: ".ssh_keys"
  changed_when: false
  register: user_keys_directory

- include_tasks: "generate-user-key.yaml"
  loop: "{{pool.value.authorized}}"
  loop_control:
    loop_var: keyname

- name: "Count user keys ..."
  find:
    path: "{{ user_keys_directory.path }}"
    file_type: file
  register: user_keys_find

- name: "Set number of keys ..."
  set_fact:
    user_keys_count: "{{ user_keys_find.files | length }}"

- name: "Update pool for {{pool.key}}"
  assemble:
    src: "{{ user_keys_directory.path }}"
    remote_src: yes
    dest: "{{ ssh_pool_dir }}/{{ pool.key }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: user_keys_count | int > 0

- name: "Purge empty pool for {{pool.key}}"
  file:
    path: "{{ ssh_pool_dir }}/{{ pool.key }}"
    state: absent
  when: user_keys_count | int == 0

- name: "Cleanup temporary key directory"
  file:
    state: absent
    path: "{{ user_keys_directory.path }}"
  changed_when: false
