---
- name: "Disable linger for user {{ rm_user }} ..."
  ansible.builtin.command: loginctl disable-linger {{ rm_user }}
  args:
    removes: "/var/lib/systemd/linger/{{ rm_user }}"

- name: "Remove user {{ rm_user }} ..."
  ansible.builtin.user:
    name: "{{ rm_user }}"
    state: absent
    force: true
    remove: true

- name: "Remove marker for user {{ rm_user }} ..."
  file:
    path: "{{wum_user_managed }}/{{ rm_user }}"
    state: absent
