- name: "Apply dummy template ..."
  set_fact:
    interface: "{{ {} | combine({'match': {'type': 'dummy' }, 'name': if_name, 'method': 'static' }) | combine(interface_entry) | combine({'use': omit}) }}"
