- name: "Apply ether/vm/dhcp template ..."
  set_fact:
    interface: "{{ {} | combine({ 'match': { 'type': 'ether', 'driver': 'vm', 'drivers': [ 'virtio_net', 'ena', 'vif' ] }, 'method': 'dhcp' }) | combine(interface_entry) | combine({'use': omit}) }}"
