- name: "Apply wlan/dhcp template ..."
  set_fact:
    interface: "{{ {} | combine({ 'match': { 'type': 'wlan', 'driver': 'any' }, 'method': 'dhcp' }) | combine(interface_entry) | combine({'use': omit}) }}"
