- name: "Install azure-cli apt repository ..."
  copy:
    src: "repository/azure-cli/debian/12/{{ repo_file.src }}"
    dest: "{{ repo_file.dst }}"
    group: root
    owner: root
    mode: 0644
    force: yes
  loop:
    - { 'src': 'azure-cli.list', 'dst': '/etc/apt/sources.list.d/azure-cli.list' }
    - { 'src': 'azure-cli.gpg',  'dst': '/usr/share/keyrings/azure-cli.gpg' }
  loop_control:
    loop_var: repo_file
    label: "{{ repo_file }}"
