- name: "Install hashicorp apt repository ..."
  copy:
    src: "repository/hashicorp/debian/12/{{ item.src }}"
    dest: "{{ item.dst }}"
    group: root
    owner: root
    mode: 0644
    force: yes
  loop:
    - { 'src': 'hashicorp.list', 'dst': '/etc/apt/sources.list.d/hashicorp.list' }
    - { 'src': 'hashicorp.gpg',  'dst': '/usr/share/keyrings/hashicorp.gpg' }
