- name: "ANSIBLE / Install pipx ..."
  include_role:
    name: wyga/install-package-override
  vars:
    packages:
      - pipx

- name: "ASIBLE / Install ansible-core ..."
  community.general.pipx:
    name: ansible-core
    install_deps: true
    global: true
    state: latest
