- name: "ANSIBLE / Install pipx ..."
  include_role:
    name: wyga/install-package-override
  vars:
    packages:
      - pipx

- name: "ASIBLE / Install ansible-core ..."
  community.general.pipx:
    name: ansible-core
    install_deps: true
  environment:
    PIPX_HOME: /opt/external/ansible-core
    PIPX_BIN_DIR: /usr/local/bin
    PIPX_MAN_DIR: /usr/local/share/man
