---
- name: "Verify configuration ..."
  assert:
    that:
      - interface.name is defined or interface.type is defined
      - interface.method is defined and interface.method in ['static', 'dhcp']
    msg: "Unable to continue, check interface configuration ..."

- name: "Verify configuration for interface.type ..."
  assert:
    that:
      - interface.name is not defined
      - interface.kind is not defined
      - interface.type in ['loopback','ether']
      - interface.method in ['static','dhcp']
    msg: "Unable to continue, check interface configuration ..."
  when: interface.type is defined

- name: "Verify configuration for interface.type=ether ..."
  assert:
    that:
      - interface.driver is defined
    msg: "Unable to continue, check interface configuration ..."
  when: interface.type is defined and interface.type == 'ether'

- name: "Verify configuration for interface.kind ..."
  assert:
    that:
      - interface.kind in ['dummy']
      - interface.method in ['static']
      - interface.gw is not defined
      - interface.route is not defined
    msg: "Unable to continue, check interface configuration ..."
  when: interface.kind is defined

- name: "Verify configuration for static interface.method..."
  assert:
    that:
      - interface.ip is defined and interface.ip | type_debug == "list"
      - ip | ipv4('address/prefix')
    msg: "Unable to continue, check interface configuration ..."
  loop: "{{ interface.ip }}"
  loop_control:
    loop_var: ip
    label: "{{ ip }}"
  when: interface.method == "static"

- name: "Verify configuration for dhcp interface.method..."
  assert:
    that:
      - interface.ip is not defined
      - interface.gw is not defined
    msg: "Unable to continue, check interface configuration ..."
  when: interface.method == "dhcp"

- name: "Verify configuration for interface.mac ..."
  assert:
    that:
      - interface.kind is not defined
      - interface.name is defined
    msg: "Unable to continue, check interface configuration ..."
  when: interface.mac is defined

- name: "Verify DNS configuration ..."
  assert:
    that:
      - interface.dns | type_debug == "list"
      - ip | ipv4('address')
    msg: "Unable to continue, check interface configuration ..."
  loop: "{{ interface.dns }}"
  loop_control:
    loop_var: ip
    label: "{{ ip }}"
  when: interface.dns is defined

- name: "Verify gw configuration ..."
  assert:
    that:
      - interface.gw | ipv4('address')
    msg: "Unable to continue, check interface configuration ..."
  when: interface.method == "static" and interface.gw is defined

- name: "Verify interface.route type ..."
  assert:
    that:
      - interface.route | type_debug == "list"
    msg: "Unable to continue, check interface configuration ..."
  when: interface.route is defined

- name: "Verify interface.route ..."
  assert:
    that:
      - route.keys() | difference(['to', 'via','onlink']) == []
      - route.to is defined
      - route.via is defined
      - route.to == "default" or route.to | ipv4('net')
      - route.via | ipv4('address')
    msg: "'to' and 'via' fields are required and must be defined, 'to' must be either 'default' or a valid IPv4 network address, and 'via' must contain a valid IPv4 address"
  loop: "{{ interface.route }}"
  loop_control:
    loop_var: route
    label: "Route ..."
  when: interface.route is defined
