---
#
#
# update-initramfs -k all -u
# may be required after .link file modifications
#
#

- name: "Prepare link changed status variable ..."
  set_fact:
    link_changed: "{{ link_changed | default(false) }}"

- name: "Link configuration ..."
  set_fact:
    link: "{{ link_entry }}"
  when: link_entry.use is not defined

- name: "Load template ..."
  include_tasks: "link/use.yaml"
  when: link_entry.use is defined

- name: "Configure wlan link ..."
  block:
    - name: "Configure wlan link ..."
      template:
        src: "network/link/wlan"
        dest: "/etc/systemd/network/00-wlan-policy.link"
        group: root
        owner: root
        mode: 0644
      register: link_change
      notify: systemd-network-update-initramfs
    - name: "Update link changed status ..."
      set_fact:
        link_changed: "{{ link_changed or link_change.changed }}"
    - name: "Mark configuration of link as managed ..."
      set_fact:
        networkd_managed_files: "{{ networkd_managed_files + [ '00-wlan-policy.link' ] }}"
  when: link.template is defined and link.template == 'wlan/policy/kernel'

- name: "Configure MAC link ..."
  block:
    - name: "Set link file suffix ..."
      set_fact:
        mac_file: "{{ link.match.mac | replace(':','' ) | upper }}"
    - name: "Configure MAC link ..."
      template:
        src: "network/link/generic"
        dest: "/etc/systemd/network/00-mac-{{ mac_file }}.link"
        group: root
        owner: root
        mode: 0644
      register: link_change
      notify: systemd-network-update-initramfs
    - name: "Update link changed status ..."
      set_fact:
        link_changed: "{{ link_changed or link_change.changed }}"
    - name: "Mark configuration of link as managed ..."
      set_fact:
        networkd_managed_files: "{{ networkd_managed_files + [ '00-mac-' ~ mac_file ~ '.link' ] }}"
  when: link.match.mac is defined

- name: "Configure interface link ..."
  block:
    - name: "Configure link ..."
      template:
        src: "network/link/generic"
        dest: "/etc/systemd/network/00-{{ link.match.name }}.link"
        group: root
        owner: root
        mode: 0644
      register: link_change
      notify: systemd-network-update-initramfs
    - name: "Update link changed status ..."
      set_fact:
        link_changed: "{{ link_changed or link_change.changed }}"
    - name: "Mark configuration of link as managed ..."
      set_fact:
        networkd_managed_files: "{{ networkd_managed_files + [ '00-' ~ link.match.name ~ '.link' ] }}"
  when: link.match.name is defined

- name: "Configure ether/policy/path link ..."
  block:
    - name: "Configure link ..."
      template:
        src: "network/link/generic"
        dest: "/etc/systemd/network/00-ether-policy.link"
        group: root
        owner: root
        mode: 0644
      register: link_change
      notify: systemd-network-update-initramfs
    - name: "Update link changed status ..."
      set_fact:
        link_changed: "{{ link_changed or link_change.changed }}"
    - name: "Mark configuration of link as managed ..."
      set_fact:
        networkd_managed_files: "{{ networkd_managed_files + [ '00-ether-policy.link' ] }}"
  when: link.template is defined and link.template == 'ether/policy/path'
