---
- name: "Load template for wlan/keep ..."
  include_tasks: "use/link/wlan-keep.yaml"
  when: link_entry.use == 'wlan/keep'

- name: "Load template for wlan/kernel ..."
  include_tasks: "use/link/wlan-kernel.yaml"
  when: link_entry.use == 'wlan/kernel'
