- name: "Apply clone template ..."
  set_fact:
    bridge:
      name: "{{ bridge_entry.name | default('host0') }}"
      mac: "clone"
      slave:
        - "{{ brparam }}"
      stp: false
      forward: 0
