- name: "Use repository parameter ..."
  set_fact:
    repository_name: "{{ repository }}"
  when: repository is defined

- name: "Check required vars ..."
  fail:
    msg: "Missing repository_name variable ..."
  when: repository_name is not defined

- name: "Install repository ..."
  include_tasks: "local/tasks/repository/{{ target_distribution }}/{{ target_distribution_version }}/{{ repository_name }}.yml"
