- name: "Check required vars ..."
  fail:
    msg: "Missing repository_name variable ..."
  when: repository_name is not defined

- name: "Install repository ..."
  include_tasks: "site/tasks/repository/{{ target_distribution }}/{{ target_distribution_version }}/{{ repository_name }}.yml"
