- name: "Use repository parameter ..."
  set_fact:
    repository_name: "{{ repository }}"
  when: repository is defined

- name: "Check required vars ..."
  fail:
    msg: "Missing repository_name variable ..."
  when: repository_name is not defined

- name: "Install repository ..."
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    repository: "{{ repository_name }}"
    target: "{{ platform.distribution }}"
    version: "{{ platform.version }}"
    arch: "{{ platform.arch.package }}"
    params:
      - files:
          - "repository/{{ repository_name }}/{{ platform.distribution }}/{{ platform.version }}/main.yaml"
          - "repository/{{ repository_name }}/common/main.yaml"
          - "local/tasks/repository/{{ platform.distribution }}/{{ platform.version }}/{{ repository_name }}.yml"
          - "local/tasks/repository/generic/{{ repository_name }}.yml"
