---
- name: "Certificate principals ..."
  set_fact:
    wyga_ssh_principals: "{{ host | ssh_host_principals(playbook_dir) }}"

- name: "Certificate state ..."
  set_fact:
    wyga_ssh_certificate_file: /etc/site/ssh/ca/certificate.yaml
    wyga_ssh_certificate_state: "{{ {'ca': lookup('file', _ca_public_file) | ssh_fingerprint, 'principal': wyga_ssh_principals} | to_nice_yaml(indent=2) }}"

- name: "Read {{ wyga_ssh_certificate_file }} ..."
  slurp:
    src: "{{ wyga_ssh_certificate_file }}"
  register: _wyga_ssh_certificate_state
  failed_when: false

- name: "Check if the certificate state changed ..."
  set_fact:
    wyga_ssh_certificate_changed: "{{ _wyga_ssh_certificate_state.content is not defined or _wyga_ssh_certificate_state.content | b64decode != wyga_ssh_certificate_state }}"
