- name: "Get a list of SSH key files ..."
  find:
    paths: "/etc/ssh"
    patterns:
      - "ssh_host_*_key"
      - "ssh_host_*_key.pub"
      - "ssh_host_*_key-cert.pub"
  register: ssh_key_files

- name: "Preare list of keys to remove ..."
  set_fact:
    keys_to_remove: []

- name: "Preare list of keys to remove ..."
  set_fact:
    keys_to_remove: "{{ keys_to_remove + [ key_file.path ] }}"
  loop: "{{ ssh_key_files.files }}"
  loop_control:
    loop_var: key_file
    label: "{{ key_file.path | basename }}"
  when: key_file.path | regex_search( wyga_ssh_host_keys | join('|')) is none

- name: "Remove SSH key files ..."
  file:
    path: "{{ key_to_remove }}"
    state: absent
  loop: "{{ keys_to_remove }}"
  notify: restart-ssh
  loop_control:
    loop_var: key_to_remove
    label: "{{ key_to_remove }}"
