---
- name: "Configure /etc/apt/apt.conf.d/99-host-policy ..."
  template:
    src: "host-certificate"
    dest: "/etc/ssh/sshd_config.d/host-certificate.conf"
    group: root
    owner: root
    mode: 0644
