- name: "Restart sshd"
  block:
    - name: Testing sshd configuration
      command: sshd -t
      register: sshd_test
      changed_when: false

    - name: Restarting sshd
      service:
        name: ssh
        state: restarted
      when: sshd_test.rc == 0
      changed_when: false
