---
- name: "Transfer certificate for {{item}} key"
  ansible.builtin.copy:
    src: "{{ _ltmp.path }}/ssh_host_{{ item }}_key-cert.pub"
    dest:  "{{ _tmp.path }}/ssh_host_{{ item }}_key-cert.pub"
    force: yes
