- name: "ANSIBLE / Install pipx ..."
  include_role:
    name: wyga/install-package-override
  vars:
    packages:
      - pipx

- name: "ASIBLE / Install ansible ..."
  community.general.pipx:
    name: ansible
    state: latest
    install_deps: true
    include_injected: true
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
    PIPX_MAN_DIR: /usr/local/share/man

- name: "ASIBLE / Incject packages  ..."
  community.general.pipx:
    name: ansible
    state: inject
    install_deps: true
    inject_packages:
      - netaddr
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
    PIPX_MAN_DIR: /usr/local/share/man
