- name: "Install hashicorp apt repository ..."
  copy:
    src: "repository/hashicorp/debian/13/{{ repo_file.src }}"
    dest: "{{ repo_file.dst }}"
    group: root
    owner: root
    mode: 0644
    force: yes
  loop:
    - { 'src': 'hashicorp.list', 'dst': '/etc/apt/sources.list.d/hashicorp.list' }
    - { 'src': 'hashicorp.gpg',  'dst': '/usr/share/keyrings/hashicorp.gpg' }
  loop_control:
    loop_var: repo_file
    label: "{{ repo_file }}"
