#jinja2: trim_blocks: True, lstrip_blocks: True
[Service]
{% for path in lukd_path %}
ReadWritePaths={{ path }}
{% endfor %}
{% if lukd_docker and role == 'process' %}
SupplementaryGroups=docker
{% endif %}
