- name: "Install docker-ce apt repository ..."
  copy:
    src: "repository/docker-ce/ubuntu/22.04/{{ item.src }}"
    dest: "{{ item.dst }}"
    group: root
    owner: root
    mode: 0644
    force: yes
  loop:
    - { 'src': 'docker.list', 'dst': '/etc/apt/sources.list.d/docker.list' }
    - { 'src': 'docker.gpg',  'dst': '/usr/share/keyrings/docker.gpg' }
