- name: "Collect only minimal facts..."
  ansible.builtin.setup:
    gather_subset:
      - 'min'
      - 'network'
      - 'mounts'

- name: "Check supported architecture ..."
  assert:
    that:
      - ansible_architecture in [ 'aarch64', 'x86_64' ]
