- name: "Collect only minimal facts..."
  ansible.builtin.setup:
    gather_subset:
      - 'min'
      - 'network'
      - 'mounts'

- name: "Identify distribution (Ubuntu) ..."
  set_fact:
    target_distribution: "{{ ansible_distribution | lower }}"
    target_distribution_version: "{{ ansible_distribution_version }}"
  when:
    -  ansible_distribution | lower == 'ubuntu'
    -  target_distribution is not defined or target_distribution_version is not defined

- name: "Identify distribution (Debian) ..."
  set_fact:
    target_distribution: "{{ ansible_distribution | lower }}"
    target_distribution_version: "{{ ansible_distribution_major_version }}"
  when:
    -  ansible_distribution | lower == 'debian'
    -  target_distribution is not defined or target_distribution_version is not defined

- name: "Check supported architecture ..."
  assert:
    that:
      - ansible_architecture in [ 'aarch64', 'x86_64' ]

- name: "Set arm64 architecture ..."
  set_fact:
    target_arch: "arm64"
  when: ansible_architecture == 'aarch64'

- name: "Set amd64 architecture ..."
  set_fact:
    target_arch: "amd64"
  when: ansible_architecture == 'x86_64'
